### ISSUE TITLE
[Entity Store / EntityGraphStore] Delete method

### ISSUE THREAD

**Issue by cjnolet** [calrissian/accumulo-recipes#99]
The delete methods need some love. The delete does not remove anything from the entity graph store and it has not been tested in the entity store for quite some time.

**Comment by vincentrussell** [comment]
I don't even see delete methods.  Are deletes supported?  I need delete capability in the EntityStore and the EventStore

**Comment by eawagner** [comment]
Hmm, this may have been before @cjnolet refactored the Entity/Event stores to use the QFDStore base. It looks like they no longer have delete methods.

I forget where he left off with the data encodings, but implementing this may be tricky considering that the caller can not ever guarantee that they are fully deleting the event (due to missing auths). Therefore all deletes would have to be treated like partial delete. This isn't hard, just some of the different entity encoding mechanisms he was trying out may require some special care to get right.

**Comment by vincentrussell** [comment]
Would you have to query the entities in order to get the attributes and create the delete mutations from that?

**Comment by eawagner** [comment]
Well, that is sort of one way, but I think you could simply delete the attributes provided for the entity. This way the user can only delete the things it has knowledge of in some way. I don't think you would need to do a query exactly, since the users would have to know the exact information about each attribute in order to successfully delete it.

I would have to look over the code, but at one point @cjnolet tried aggregating multiple attributes into a single value for the shard entries in order to get better compression. That was the encoding mechanism I was referring to.  I wasn't sure if that was still in play.

**Comment by vincentrussell** [comment]
Well..that's my point.  I don't see how you can delete the attributes without querying for them first.   Looking at the code it looks like every attribute has it's own entry.

**Comment by vincentrussell** [comment]
Also,  can we talk about cutting a release?  At least a release candidate?   What's this process?  I would like to help with this.  especially if we get deletes done.

**Comment by vincentrussell** [comment]
This is what I came up with so far:
https://github.com/calrissian/accumulo-recipes/tree/issues/99/delete

**Comment by eawagner** [comment]
What I meant was that you don't need to requery in the delete method.  So for example if someone provides an Entity object which has attributes, those can be converted to rows and deleted.  I was just saying you didn't need to query because information about those entities and attributes may have come from some other mechanism, i.e. a cache or other external storage.

**Comment by eawagner** [comment]
I noticed a few small things with the changes in that branch.  It would be easier to go over it in a merge request since I can comment on the line.

For instance, you should simply make the delete take in Entities, and not requery the entire entity.  This way you can delete portions of entities if you wanted to. Also I would avoid using collections on those methods since they are often capable of working just fine with very very large sets of Entities.

As for releases, you should probably hit up @cjnolet or I via email. We can dig up the information required to get the accounts and such set up in order to start with the release process.

**Comment by vincentrussell** [comment]
ok.. just did a merge request.
